# Ingress resource for the application
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: goweb-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: golang-web-app.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: goweb-app
            port:
              number: 80
